### ISSUE TITLE
Having a class property causes error

### ISSUE THREAD

**Issue by flowers3176** [roblox-csharp/roblox-cs#4]
having the static boolean "debounce" variable inside the Game class breaks the compiler

```cs
using static Roblox.Globals;
using Roblox;


namespace Hello_CS.Client
{
    public static class Game
    {
        static bool debounce = false;
        public static void Main()
        {
            Workspace workspace = Services.Workspace;
            Part part = Instance.Create<Part>();
            part.Parent = workspace;
            part.Position = new Vector3(10, 10, 10);
            part.Anchored = false;
            part.Touched.Connect(OnTouched);
        }

        public static void OnTouched(BasePart Hit)
        {
            Instance? Character = Hit.Parent;
            if (Character == null) return;
            Humanoid? Humanoid = Character.FindFirstChildOfClass<Humanoid>();
            if (Humanoid == null) return;
            if (debounce) return;
            void resetDebounce()
            {
                debounce = false;
            }
            debounce = true; task.delay((float)0.1, resetDebounce);
            Humanoid.TakeDamage(10);
        }
    }
}
```

**Comment by flowers3176** [comment]
```Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at RobloxCS.CodeGenerator.GetName(SyntaxNode node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 1400
   at RobloxCS.CodeGenerator.<>c__DisplayClass55_0.<VisitIdentifierName>b__5(MemberDeclarationSyntax member) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 898
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at RobloxCS.CodeGenerator.VisitIdentifierName(IdentifierNameSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 897
   at Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitArgument(ArgumentSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RobloxCS.CodeGenerator.VisitArgumentList(ArgumentListSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 541
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RobloxCS.CodeGenerator.VisitInvocationExpression(InvocationExpressionSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 655
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitExpressionStatement(ExpressionStatementSyntax node)
   at RobloxCS.CodeGenerator.VisitExpressionStatement(ExpressionStatementSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 532
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RobloxCS.CodeGenerator.VisitMethodDeclaration(MethodDeclarationSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 1187
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RobloxCS.CodeGenerator.VisitClassDeclaration(ClassDeclarationSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 1129
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RobloxCS.CodeGenerator.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 1059
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at RobloxCS.CodeGenerator.GenerateLua() in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\CodeGenerator.cs:line 64
   at RobloxCS.TranspilerUtility.GenerateLua(SyntaxTree tree, CSharpCompilation compiler, MemberCollectionResult members, String inputDirectory, ConfigData config) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\TranspilerUtility.cs:line 44
   at RobloxCS.Transpiler.WriteLuaOutput(CSharpCompilation compiler) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\Transpiler.cs:line 97
   at RobloxCS.Transpiler.Transpile() in C:\Users\sivak\source\repos\roblox-cs\RobloxCS\Transpiler.cs:line 29
   at RobloxCS.CLI.Program.Main(String[] args) in C:\Users\sivak\source\repos\roblox-cs\RobloxCS.CLI\Program.cs:line 9```

**Comment by flowers3176** [comment]
Works if i remove `static bool debounce = false;`
still broken even if debounce is a diff type

**Comment by R-unic** [comment]
Please try running `git pull` in your roblox-cs installation and then recompile roblox-cs. Then try compiling your code again and let me know the result. I can't see the actual line the error is on currently since I added things since you cloned the repository.

**Comment by flowers3176** [comment]
Building roblox-cs gives this error but building the cli works fine
```Build FAILED.

C:\Users\sivak\source\repos\roblox-cs\TestProject\TestProject.csproj(15,5): error MSB3073: The command ""C:/Users/Riley Peel/dev/c#/roblox-cs/RobloxCS.CLI/bin/Release/net8.0/roblox-cs.exe"" exited with code 3.
    0 Warning(s)
    1 Error(s)```

**Comment by flowers3176** [comment]
> Please try running `git pull` in your roblox-cs installation and then recompile roblox-cs. Then try compiling your code again and let me know the result. I can't see the actual line the error is on currently since I added things since you cloned the repository.

Yes! that fixed the issue tysm

**Comment by R-unic** [comment]
> Building roblox-cs gives this error but building the cli works fine
> 
> ```
> 
> C:\Users\sivak\source\repos\roblox-cs\TestProject\TestProject.csproj(15,5): error MSB3073: The command ""C:/Users/Riley Peel/dev/c#/roblox-cs/RobloxCS.CLI/bin/Release/net8.0/roblox-cs.exe"" exited with code 3.
>     0 Warning(s)
>     1 Error(s)```
> ```

Will be fixijng this momentarily, it's also why the workflows are failing lol
